### PR TITLE
fix: restore loading all imgs in mediabus 

### LINKED ISSUE #268: Restrict the origins the MediaHandler passes the authorization header to
**Description**
html2md accepts an authorization header, which is passed-through the MediaHandler to fetch all the images in a document and upload them to the media bus. This is not limited to the trusted origin the authorization header is meant to be used for. 

This could eventually be misused to obtain the authorization header by adding an image hosted on a 3rd-party origin that can log the authorization header. If the system that integrates that way uses a service user and sends the according authorization header it may allow an author to escalate permissions.   

**To Reproduce**
1. Create a service that hosts an image and logs all http headers
2. Add a reference to the image to a the document being fetched by html2md
3. Call html2md with an authorization header
4. See the header being logged in the 3rd-party service

**Expected behavior**
The authorization token should only be passed-through to trusted origins, e.g. only to the same-origin as in the fstab.yaml. Ideally we could add other origins we own and know are secure (like AEM CS, Dynamic Media, Polaris).  

Alternatively we could skip loading images into the media bus for assets hosted on Adobe's own image delivery infrastructures (like Dynamic Media or Polaris). In that case we would eventually have additional efforts when using the `createOptimizedImage()` boilerplate method - or at least this would mean some additional efforts in a project. 

Not sure what the right approach would be.

**Additional context**
With Crosswalk we aim to publish existing AEM content to the helix delivery infrastructure. To do so we use a serverless worker that transforms the markup rendered by AEM to html the html2md can work with. In the fstab.yaml we point to this serverless worker (aka converter). It would be possible to rewrite image references to point to the same origin (the converter) but that would mean we have to proxy the binaries as well. Ideally we could rewrite the images in a way that they are directly loaded from an AEM CS environment.

### PR DESCRIPTION
**Pull request by Buuhuu**
Urls that are not within the specified img-src policy will be requested without passing through the authorization header.

Fixes #268

Please ensure your pull request adheres to the following guidelines:
- [x] make sure to link the related issues in this description
- [x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -93,15 +93,16 @@ async function run(request, ctx) {
   }
 
   // only use media handler when loaded via fstab. otherwise images are not processed.
-  let mediaHandler;
+  let mediaHandlerWithAuth;
+  let mediaHandlerWithoutAuth;
```
Comment (tripodsan) [inline src/index.js:97]: this is a bit ugly... could enhance the media handler to allow to pass a function for the `auth` option, so this could be provided dynamically.

Comment (tripodsan) [reply src/index.js:97]: added: https://github.com/adobe/helix-mediahandler/commit/b6c02a350e3cbe0a2409776483dbbd8aa4bea1c1#diff-583c6d206b4d52be0d0cfec9734827c41f39f3ece1de8dd4d232acb95fe3d03aR139

Comment (Buuhuu) [reply src/index.js:97]: love it, thank you.

**Review by tripodsan — APPROVED** [review]
